spring:
  application.name: passwordService
#  jackson.mapper:
#    com.dcai.password.service.model.User: userMapper
  jackson.serialization.indent_output: true
    
server:
  port: 8100
#  ssl:
#    key-password: password
#    key-store:  classpath:selfsigned.jks
#    key-store-type: JKS
  error.whitelabel.enabled: true
    
security:
  basic:
    enabled: true
  oauth2:
    client:
      clientId: 1046534738592-9800q0ich0f5h6340a5f3hpfnu5btase.apps.googleusercontent.com
      clientSecret: kdtkjWb_Ej0oTqS3aJwDXQXa
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      tokenName: PasswdService
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile
    resource:
        userInfoUri: https://www.googleapis.com/userinfo/v2/me
        preferTokenInfo: false

# file:
#  password: <path to your passwd file, default to /etc/passwd>
#    field:
#      delimiter: <default to ':'>
#    commentMarker: <default to hash sign>
#  groups: <path to your groups file, default to /etc/groups>
#    field:
#      delimiter: <default to ':'>
#    commentMarker: <default to hash sign>